//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoportePatitosBD.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asistencia
    {
        [Display(Name = "ID")]
        public int ID_asistencia { get; set; }
        public int Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cedula { get; set; }
        public int ID_Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipo Tipo1 { get; set; }
    }
}
