//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoportePatitosBD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int ID_planilla { get; set; }
        public int Cedula { get; set; }
        public int Salario_bruto { get; set; }
        public double Deducciones_fiscales { get; set; }
        public double Deducciones_CCSS { get; set; }
        public double Deducciones_ausencias { get; set; }
        public double Salario_neto { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
