//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoportePatitosBD.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Planilla
    {
        [Display(Name = "ID planilla")]
        public int ID_planilla { get; set; }
        [Display(Name = "Cédula")]
        public int Cedula { get; set; }
        [Display(Name = "Salario Bruto")]
        public int Salario_bruto { get; set; }
        [Display(Name = "Renta")]
        public double Deducciones_fiscales { get; set; }
        [Display(Name = "Rebajo CCSS")]
        public double Deducciones_CCSS { get; set; }
        [Display(Name = "Rebajo por ausencias")]
        public double Deducciones_ausencias { get; set; }
        [Display(Name = "Salario neto")]
        public double Salario_neto { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
